Spring data jpa
vrudkovsky/OnlineBookStore pull request #2
Opened 2024-03-22 02:19 UTC by vrudkovsky

2024-03-22 17:40 UTC, okuzan requested changes
extract /api to project-wide prefix using relevent property in application.properties

2024-03-22 17:40 UTC, okuzan commented on src/main/java/com/vpcomtek/onlinebookstore/model/Book.java
> +//@Table(name = "book")
don't forget to remove comments before committing
```suggestion
@SQLDelete(sql = "UPDATE book SET is_deleted = TRUE WHERE id = ?")
@SQLRestriction(clause = "is_deleted = FALSE")
```

2024-03-22 17:40 UTC, okuzan commented on src/main/resources/db/changelog/changes/01-create-table-book.yaml
> +                  type: varchar(255)
don't forget to leave last line of the file empty
![image](https://github.com/vrudkovsky/OnlineBookStore/assets/49767049/79ebe56b-84ca-473f-a61c-f0b62c41da1a)

2024-03-22 17:40 UTC, okuzan commented on src/main/resources/db/changelog/changes/02-add-column-isDeleted.yaml
> +                    nullable: false
```suggestion
                    nullable: false

```

2024-03-22 17:40 UTC, okuzan commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/02-add-column-isDeleted.yaml
```suggestion
      file: db/changelog/changes/02-add-column-isDeleted.yaml

```

2024-03-24 13:41 UTC, okuzan commented on src/main/java/com/vpcomtek/onlinebookstore/model/Book.java
> +//@Table(name = "book")
not fixed

2024-04-04 09:10 UTC, Vasul-Pankiv approved these changes

2024-04-04 14:21 UTC, merged